[package]
name = "dwfft3d"
version = "0.1.0"
authors = ["Junwen Li <junwen.li@dftworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
ndarray = { path = "../ndarray" }
num-complex = "0.4"
cfg-if = "1.0"
##########
[features]
cpu = []
gpu = []
default = ["cpu"]  

