use crate::types::TrialOrbital;
use control::Control;
use crystal::Crystal;
use dwconsts::BOHR_TO_ANG;
use kpts::KPTS;
use std::fs::File;
use std::io::{self, BufWriter, Write};

pub(crate) fn write_win_file(
    filename: &str,
    control: &Control,
    crystal: &Crystal,
    kpts: &dyn KPTS,
    spin_channel: Option<&str>,
    trial_orbitals: &[TrialOrbital],
) -> io::Result<()> {
    let file = File::create(filename)?;
    let mut writer = BufWriter::new(file);

    writeln!(
        writer,
        "! Generated by dftworks. Edit projections/advanced options as needed."
    )?;
    writeln!(writer, "num_bands = {}", control.get_nband())?;
    writeln!(writer, "num_wann = {}", control.get_wannier90_num_wann())?;
    writeln!(writer, "num_iter = {}", control.get_wannier90_num_iter())?;

    if let Some(channel) = spin_channel {
        writeln!(writer, "spin = {}", channel)?;
    }

    let k_mesh = kpts.get_k_mesh();
    writeln!(
        writer,
        "mp_grid = {} {} {}",
        k_mesh[0], k_mesh[1], k_mesh[2]
    )?;
    writeln!(writer)?;

    writeln!(writer, "begin unit_cell_cart")?;
    writeln!(writer, "ang")?;
    let a = crystal.get_latt().get_vector_a();
    let b = crystal.get_latt().get_vector_b();
    let c = crystal.get_latt().get_vector_c();
    writeln!(
        writer,
        "  {:>18.10} {:>18.10} {:>18.10}",
        a.x * BOHR_TO_ANG,
        a.y * BOHR_TO_ANG,
        a.z * BOHR_TO_ANG
    )?;
    writeln!(
        writer,
        "  {:>18.10} {:>18.10} {:>18.10}",
        b.x * BOHR_TO_ANG,
        b.y * BOHR_TO_ANG,
        b.z * BOHR_TO_ANG
    )?;
    writeln!(
        writer,
        "  {:>18.10} {:>18.10} {:>18.10}",
        c.x * BOHR_TO_ANG,
        c.y * BOHR_TO_ANG,
        c.z * BOHR_TO_ANG
    )?;
    writeln!(writer, "end unit_cell_cart")?;
    writeln!(writer)?;

    writeln!(writer, "begin atoms_frac")?;
    for (species, position) in crystal
        .get_atom_species()
        .iter()
        .zip(crystal.get_atom_positions().iter())
    {
        writeln!(
            writer,
            "  {:<4} {:>16.10} {:>16.10} {:>16.10}",
            species, position.x, position.y, position.z
        )?;
    }
    writeln!(writer, "end atoms_frac")?;
    writeln!(writer)?;

    writeln!(writer, "begin projections")?;
    writeln!(
        writer,
        "! DFTWorks reads this block when generating .amn (w90-amn)."
    )?;
    writeln!(
        writer,
        "! Add one or more entries like `Si1:sp3` or `O:s;p` as needed."
    )?;
    writeln!(
        writer,
        "! If this block is left empty, pseudo-atomic PP_CHI defaults are used."
    )?;
    writeln!(
        writer,
        "! default PP_CHI-derived orbitals (index: atom/species l m):"
    )?;
    for (i, orb) in trial_orbitals.iter().enumerate() {
        writeln!(
            writer,
            "! {:3}: atom#{:3} {:<6} l={} m={}",
            i + 1,
            orb.atom_index + 1,
            orb.species,
            orb.l,
            orb.m
        )?;
    }
    writeln!(writer, "end projections")?;
    writeln!(writer)?;

    writeln!(writer, "begin kpoints")?;
    for ik in 0..kpts.get_n_kpts() {
        let k = kpts.get_k_frac(ik);
        writeln!(writer, "  {:>16.10} {:>16.10} {:>16.10}", k.x, k.y, k.z)?;
    }
    writeln!(writer, "end kpoints")?;

    writer.flush()?;
    Ok(())
}
